# Generated by Django 3.0.4 on 2020-04-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('categories', models.ManyToManyField(related_name='items', to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemFileVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='item/video')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_video', to='main.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFilePdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='item/pdf')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_pdf', to='main.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFileAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='item/audio')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_audio', to='main.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('tags', models.ManyToManyField(related_name='items_components', to='main.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='components',
            field=models.ManyToManyField(related_name='items', to='main.ItemComponent'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='items', to='main.Tag'),
        ),
    ]
